In [22]:
import numpy as np
import pandas as pd
import read_tech_compaines as c
import read_mta_turnstile as t

In [2]:
def read_mta_stations():
    ''' Read the MTA master list into a pd.DataFrame (Put the CSV file on the repository!!)
    data source = https://data.cityofnewyork.us/Transportation/Subway-Stations/arq3-7z49 (export data as csv)
    '''
    df = pd.read_csv("mta_stations.csv")
    df.rename(columns = {"OBJECTID": "key", "NAME":"name", "the_geom":"location"}, inplace = True)
    
    df["lon"] = df.location.str.split().str.get(1).str.strip('(')
    df["lat"] = df.location.str.split().str.get(2).str.strip(')')
    df = df[["name","LINE","lon","lat"]]
    df = df.sort_values(["name","LINE"], ascending = [True, True]).reset_index()
    
    return df
    
    '''
    return pd.DataFrame (columns = [station (unique), lattitude, longitude])
    '''

In [3]:
stations = read_mta_stations()

In [4]:
stations[stations.name.isnull()]

Empty DataFrame
Columns: [index, name, LINE, lon, lat]
Index: []

In [5]:
stations[stations.lon.isnull()]

Empty DataFrame
Columns: [index, name, LINE, lon, lat]
Index: []

In [6]:
stations[stations.lat.isnull()]

Empty DataFrame
Columns: [index, name, LINE, lon, lat]
Index: []

In [7]:
companies = c.read_tech_companies()

In [8]:
companies

                     COMPANY        LAT        LON
0   Accenture Content Studio  40.725410 -74.004690
1                  Accenture  40.763000 -73.979030
2               Thoughtworks  40.744678 -73.984901
3                     Amazon  40.753050 -73.999440
4            Bank of America  40.755390 -73.984710
5                   Facebook  40.730701 -73.991531
6                         HP  40.744830 -73.999460
7                  Microsoft  40.756989 -73.989708
8                  Two Sigma  40.723270 -74.004390
9                    Workday  40.748170 -73.985000
10               Capital One  40.756020 -73.974180
11                      Ebay  40.740210 -73.994990
12                    Google  40.798939 -73.024742
13                       PWC  40.752650 -73.980030

In [9]:
stations.sample(5)

     index                 name   LINE                 lon                 lat
140    107              7th Ave    F-G  -73.98025117900944   40.66624469001985
244     34          Chauncey St    J-Z  -73.91038357033376   40.68285130087804
20     439             135th St  A-B-C  -73.94753480879213  40.817905559212676
227    281  Bushwick - Aberdeen      L  -73.90526176305106   40.68286062551184
339    367   Jay St - MetroTech  A-C-F  -73.98721815267317  40.692470636847084

In [10]:
companies.sample(5)

                     COMPANY        LAT        LON
0   Accenture Content Studio  40.725410 -74.004690
5                   Facebook  40.730701 -73.991531
9                    Workday  40.748170 -73.985000
12                    Google  40.798939 -73.024742
6                         HP  40.744830 -73.999460

In [11]:
companies['key'] = 0
stations['key'] = 0
cs = companies.merge(stations, how='left', on = 'key')
cs.drop('key',1, inplace=True)

In [12]:
cs.sample(0)

Empty DataFrame
Columns: [COMPANY, LAT, LON, index, name, LINE, lon, lat]
Index: []

In [13]:
from geopy.distance import geodesic as gd

In [14]:
def dist_calc(row):
    start = (row['LAT'], row['LON'])
    end = (row['lat'], row['lon'])
    return gd(start,end).miles

cs['distance'] = cs.apply(lambda row: dist_calc(row), axis =1)
cs

,COMPANY,LAT,LON,index,name,LINE,lon,lat,distance
0,Accenture Content Studio,40.72541,-74.00469,158,103rd St,1,-73.96837899960818,40.799446000334825,5.452357
1,Accenture Content Studio,40.72541,-74.00469,457,103rd St,4-6-6 Express,-73.94747800152219,40.79060000008452,5.407965
2,Accenture Content Studio,40.72541,-74.00469,160,103rd St,A-B-C,-73.96137008267617,40.796060739904526,5.378911
3,Accenture Content Studio,40.72541,-74.00469,188,103rd St - Corona Plaza,7,-73.86269999830412,40.749865000555545,7.641133
4,Accenture Content Studio,40.72541,-74.00469,97,104th St,A-S,-73.83768300060997,40.681711001091195,9.273881
5,Accenture Content Studio,40.72541,-74.00469,13,104th-102nd Sts,J-Z,-73.84443500029684,40.69516599823373,8.669501
6,Accenture Content Studio,40.72541,-74.00469,449,110th St,4-6-6 Express,-73.94424999687163,40.795020000113105,5.755686
7,Accenture Content Studio,40.72541,-74.00469,189,111th St,7,-73.85533399834884,40.75172999941711,8.046613
8,Accenture Content Studio,40.72541,-74.00469,82,111th St,A-S,-73.83216299845388,40.68433100001238,9.492756
9,Accenture Content Studio,40.72541,-74.00469,208,111th St,J,-73.83679338454697,40.697114810696476,9.029305
10,Accenture Content Studio,40.72541,-74.00469,169,116th St,2-3,-73.94962500096905,40.802097999133004,6.028960
11,Accenture Content Studio,40.72541,-74.00469,461,116th St,4-6-6 Express,-73.9416169983714,40.7986290002001,6.039617
12,Accenture Content Studio,40.72541,-74.00469,397,116th St,A-B-C,-73.95479778057312,40.80505813344211,6.087452
13,Accenture Content Studio,40.72541,-74.00469,166,116th St - Columbia University,1,-73.96410999757751,40.807722001230864,6.065657
14,Accenture Content Studio,40.72541,-74.00469,209,121st St,J-Z,-73.82834900017954,40.700481998515315,9.417263
15,Accenture Content Studio,40.72541,-74.00469,286,125th St,1,-73.95837200097044,40.815580999978934,6.679688
16,Accenture Content Studio,40.72541,-74.00469,167,125th St,2-3,-73.94549500011411,40.807753999182815,6.475285
17,Accenture Content Studio,40.72541,-74.00469,467,125th St,4-5-6-6 Express,-73.93759400055725,40.804138000587244,6.473265
18,Accenture Content Studio,40.72541,-74.00469,398,125th St,A-B-C-D,-73.95224799734774,40.811071672994565,6.519811
19,Accenture Content Studio,40.72541,-74.00469,168,135th St,2-3,-73.94077000106708,40.8142290003391,6.986154
20,Accenture Content Studio,40.72541,-74.00469,439,135th St,A-B-C,-73.94753480879213,40.817905559212676,7.051650
21,Accenture Content Studio,40.72541,-74.00469,171,137th St - City College,1,-73.95367600087873,40.82200799968475,7.182681
22,Accenture Content Studio,40.72541,-74.00469,140,138th St - Grand Concourse,4-5,-73.92984899935611,40.81322399958908,7.220244
23,Accenture Content Studio,40.72541,-74.00469,155,145th St,1,-73.95035999879713,40.82655099962194,7.538499
24,Accenture Content Studio,40.72541,-74.00469,172,145th St,3,-73.93624499873299,40.82042099969279,7.474849
25,Accenture Content Studio,40.72541,-74.00469,294,145th St,A-B-C-D,-73.94408792823116,40.824766360871905,7.557052
26,Accenture Content Studio,40.72541,-74.00469,288,149th St - Grand Concourse,2-5,-73.92672247438611,40.81833014409742,7.605237
27,Accenture Content Studio,40.72541,-74.00469,46,149th St - Grand Concourse,4,-73.9273847542618,40.81830344372315,7.585053
28,Accenture Content Studio,40.72541,-74.00469,438,14th St,1-2-3,-74.00020100063497,40.737825999728116,0.888547
29,Accenture Content Studio,40.72541,-74.00469,443,14th St,A-C-E,-74.00168999937027,40.740893000193296,1.079908
...,...,...,...,...,...,...,...,...,...
6592,PWC,40.75265,-73.98003,170,Tremont Ave,B-D,-73.90522700122354,40.850409999510234,7.803212
6593,PWC,40.75265,-73.98003,104,Union Sq - 14th St,4-5-6-6 Express,-73.98995099881881,40.734673000996125,1.345301
6594,PWC,40.75265,-73.98003,383,Union Sq - 14th St,L,-73.99066976901818,40.73476331217923,1.354665
6595,PWC,40.75265,-73.98003,378,Union Sq - 14th St,N-Q-R-W,-73.99053886181645,40.73587226699812,1.282362
6596,PWC,40.75265,-73.98003,35,Union St,D-N-R,-73.98310999909673,40.67731566735096,5.200755
6597,PWC,40.75265,-73.98003,297,Utica Ave,A-C,-73.93072899914027,40.67936399950546,5.680872
6598,PWC,40.75265,-73.98003,270,Van Cortlandt Park - 242nd St,1,-73.89858300049647,40.88924800011476,10.347617
6599,PWC,40.75265,-73.98003,45,Van Siclen Ave,3-4,-73.88940491730106,40.665517963059635,7.667582
6600,PWC,40.75265,-73.98003,213,Van Siclen Ave,A-C,-73.8903580002471,40.67270999906104,7.252210
6601,PWC,40.75265,-73.98003,11,Van Siclen Ave,J-Z,-73.89165772702445,40.67802821447783,6.931172
6602,PWC,40.75265,-73.98003,100,Vernon Blvd - Jackson Ave,7-7 Express,-73.95358099875249,40.74262599969749,1.550790
6603,PWC,40.75265,-73.98003,83,W 4th St - Washington Sq (Lower),B-D-F-M,-74.00030814755975,40.732254493367876,1.764433
6604,PWC,40.75265,-73.98003,205,W 4th St - Washington Sq (Upper),A-C-E,-74.00049500225435,40.73233799774325,1.765788
6605,PWC,40.75265,-73.98003,197,W 8th St - NY Aquarium,F-Q,-73.97595787413822,40.576033818103646,12.188690
6606,PWC,40.75265,-73.98003,279,Wakefield - 241st St,2,-73.8506199987954,40.903125000541245,12.402524
6607,PWC,40.75265,-73.98003,429,Wall St,2-3,-74.00909999844257,40.706820999753376,3.511230
6608,PWC,40.75265,-73.98003,419,Wall St,4-5,-74.01186199860112,40.70755700086603,3.531796
6609,PWC,40.75265,-73.98003,271,West Farms Sq - E Tremont Av,2-5,-73.87996127877184,40.84020763241799,8.002493
6610,PWC,40.75265,-73.98003,201,Westchester Sq - E Tremont Ave,6-6 Express,-73.84295199925012,40.839892001013915,9.376164
6611,PWC,40.75265,-73.98003,420,Whitehall St,R-W,-74.0130072374272,40.703142373599135,3.829718
6612,PWC,40.75265,-73.98003,51,Whitlock Ave,6,-73.8862829985325,40.82652500055904,7.082250
6613,PWC,40.75265,-73.98003,73,Wilson Ave,L,-73.90395860491864,40.68886654246024,5.943077
6614,PWC,40.75265,-73.98003,44,Winthrop St,2-5,-73.95007934590994,40.65665931376077,6.807730
6615,PWC,40.75265,-73.98003,207,Woodhaven Blvd,J-Z,-73.85205199740794,40.69370399880105,7.853793
6616,PWC,40.75265,-73.98003,231,Woodhaven Blvd - Queens Mall,E-M-R,-73.86943208612348,40.73309737380972,5.959120
6617,PWC,40.75265,-73.98003,455,Woodlawn,4,-73.87875099990931,40.886037000253324,10.625654
6618,PWC,40.75265,-73.98003,53,Woodside - 61st St,7-7 Express,-73.90298400173006,40.745630001138395,4.072048
6619,PWC,40.75265,-73.98003,408,World Trade Center,E,-74.00974461517701,40.71256392680817,3.175482
6620,PWC,40.75265,-73.98003,451,York St,F,-73.98688499993673,40.699742667691574,3.668426
6621,PWC,40.75265,-73.98003,29,Zerega Ave,6-6 Express,-73.8470359987544,40.836488000608156,9.061400

In [15]:
min_d = (
            cs.
            sort_values(by =['COMPANY', 'distance'], ascending = [True, True]).
            groupby('COMPANY').
            head(5).
            reset_index()
        )

In [16]:
min_d.rename(columns={'name':'stations'}, inplace = True)

In [17]:
min_d = min_d[min_d.distance <= 0.25]

In [20]:
min_d

,level_0,COMPANY,LAT,LON,index,stations,LINE,lon,lat,distance
0,584,Accenture,40.763000,-73.979030,349,57th St,F,-73.97736800085171,40.76408500081713,0.114929
1,611,Accenture,40.763000,-73.979030,347,7th Ave,B-D-E,-73.98169782344476,40.76297015245628,0.139985
2,585,Accenture,40.763000,-73.979030,354,57th St,N-Q-R-W,-73.98072973372128,40.76456552501829,0.140079
5,431,Accenture Content Studio,40.725410,-74.004690,394,Spring St,A-C-E,-74.00373899843763,40.72622700129312,0.075302
6,228,Accenture Content Studio,40.725410,-74.004690,89,Canal St,1-2,-74.0062770001748,40.72285399778783,0.195057
7,326,Accenture Content Studio,40.725410,-74.004690,96,Houston St,1-2,-74.00536700180581,40.728251000730204,0.199231
10,1503,Amazon,40.753050,-73.999440,469,34th St - Hudson Yards,7-7 Express,-74.00219709442206,40.75544635961596,0.219710
15,1987,Bank of America,40.755390,-73.984710,59,42nd St - Bryant Pk,B-D-F-M,-73.98459099904711,40.754184001312545,0.083451
16,2334,Bank of America,40.755390,-73.984710,146,Times Sq - 42nd St,S,-73.98622899953202,40.755983000570076,0.089594
17,2333,Bank of America,40.755390,-73.984710,79,Times Sq - 42nd St,N-Q-R-W,-73.98676800153976,40.75461199851542,0.120596
18,2331,Bank of America,40.755390,-73.984710,358,Times Sq - 42nd St,1-2-3,-73.98749500051885,40.75528999995681,0.146297
19,2332,Bank of America,40.755390,-73.984710,196,Times Sq - 42nd St,7-7 Express,-73.98769099825152,40.755477001982506,0.156534
20,4837,Capital One,40.756020,-73.974180,84,51st St,4-6-6 Express,-73.97192000069982,40.75710699989316,0.140315
25,5233,Ebay,40.740210,-73.994990,440,14th St,F-M,-73.99620899921355,40.73822799969515,0.150988
26,5259,Ebay,40.740210,-73.994990,202,18th St,1-2,-73.99787100060406,40.741039999802105,0.161688
27,5277,Ebay,40.740210,-73.994990,364,23rd St,F-M,-73.99276500471389,40.742954317826005,0.222475
28,5329,Ebay,40.740210,-73.994990,441,6th Ave,L,-73.99775078874781,40.73774146981052,0.223629
30,2529,Facebook,40.730701,-73.991531,0,Astor Pl,4-6-6 Express,-73.99106999861966,40.73005400028978,0.050781
31,2518,Facebook,40.730701,-73.991531,400,8th St - NYU,N-Q-R-W,-73.99250799849149,40.73046499853991,0.053808
40,2911,HP,40.744830,-73.999460,435,23rd St,A-C-E,-73.99804100117201,40.74590599939995,0.105158
41,2909,HP,40.744830,-73.999460,95,23rd St,1-2,-73.9956570016487,40.74408099989751,0.206167
45,3407,Microsoft,40.756989,-73.989708,361,42nd St - Port Authority Bus Term,A-C-E,-73.98973500085859,40.757307998551504,0.022057
46,3751,Microsoft,40.756989,-73.989708,196,Times Sq - 42nd St,7-7 Express,-73.98769099825152,40.755477001982506,0.148614
47,3750,Microsoft,40.756989,-73.989708,358,Times Sq - 42nd St,1-2-3,-73.98749500051885,40.75528999995681,0.165009
48,3753,Microsoft,40.756989,-73.989708,146,Times Sq - 42nd St,S,-73.98622899953202,40.755983000570076,0.195300
49,3752,Microsoft,40.756989,-73.989708,79,Times Sq - 42nd St,N-Q-R-W,-73.98676800153976,40.75461199851542,0.225168
50,6460,PWC,40.752650,-73.980030,80,Grand Central - 42nd St,S,-73.97918899989101,40.75276866674217,0.044884
51,6267,PWC,40.752650,-73.980030,465,5th Ave - Bryant Pk,7-7 Express,-73.98196299856706,40.75382100064824,0.129682
52,6458,PWC,40.752650,-73.980030,30,Grand Central - 42nd St,4-5-6-6 Express,-73.9767132992584,40.75180742981634,0.183496
53,6459,PWC,40.752650,-73.980030,203,Grand Central - 42nd St,7-7 Express,-73.97604100111508,40.751431000286864,0.225589
55,1025,Thoughtworks,40.744678,-73.984901,199,28th St,4-6-6 Express,-73.98426400110407,40.743069999259035,0.115883
56,1028,Thoughtworks,40.744678,-73.984901,31,33rd St,4-6-6 Express,-73.98207600148947,40.74608099909145,0.177065
57,1026,Thoughtworks,40.744678,-73.984901,143,28th St,N-Q-R-W,-73.98869800128737,40.74545399979951,0.206336
60,4012,Two Sigma,40.723270,-74.004390,89,Canal St,1-2,-74.0062770001748,40.72285399778783,0.103138
61,4017,Two Sigma,40.723270,-74.004390,409,Canal St - Holland Tunnel,A-C-E,-74.0052290023424,40.72082400007119,0.174432
62,4215,Two Sigma,40.723270,-74.004390,394,Spring St,A-C-E,-74.00373899843763,40.72622700129312,0.206882
65,4579,Workday,40.748170,-73.985000,365,Herald Sq - 34th St,B-D-F-M,-73.98777189072918,40.74978939990011,0.183426
66,4580,Workday,40.748170,-73.985000,144,Herald Sq - 34th St,N-Q-R-W,-73.9879368338264,40.74964456009442,0.184674
67,4339,Workday,40.748170,-73.985000,31,33rd St,4-6-6 Express,-73.98207600148947,40.74608099909145,0.210533

In [18]:
min_d2 = min_d.loc[:,['COMPANY','stations','distance']]

In [26]:
com_count = min_d2.groupby('stations').count().sort_values(by='COMPANY',ascending = False)

In [31]:
entry = t.read_mta_turnstile(start='20180501', end='20180531')

Reading: http://web.mta.info/developers/data/nyct/turnstile/turnstile_180505.txt
Reading: http://web.mta.info/developers/data/nyct/turnstile/turnstile_180512.txt
Reading: http://web.mta.info/developers/data/nyct/turnstile/turnstile_180519.txt
Reading: http://web.mta.info/developers/data/nyct/turnstile/turnstile_180526.txt
Reading: http://web.mta.info/developers/data/nyct/turnstile/turnstile_180602.txt

In [32]:
entry

,index,CA,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,date_time,hour,entries_offset,exits_offset,hourly_entries,hourly_exits
0,30193,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,00:00:00,REGULAR,13470157,15068968.0,2018-04-28 00:00:00,0,13470247,15069262.0,90.0,294.0
1,30194,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,04:00:00,REGULAR,13470247,15069262.0,2018-04-28 04:00:00,4,13470336,15069583.0,89.0,321.0
2,30195,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,08:00:00,REGULAR,13470336,15069583.0,2018-04-28 08:00:00,8,13470882,15070622.0,546.0,1039.0
3,30196,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,12:00:00,REGULAR,13470882,15070622.0,2018-04-28 12:00:00,12,13471623,15071910.0,741.0,1288.0
4,30197,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,16:00:00,REGULAR,13471623,15071910.0,2018-04-28 16:00:00,16,13472316,15073470.0,693.0,1560.0
5,30198,H007,R248,00-00-00,1 AV,L,BMT,04/28/2018,20:00:00,REGULAR,13472316,15073470.0,2018-04-28 20:00:00,20,13472821,15074492.0,505.0,1022.0
6,30199,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,00:00:00,REGULAR,13472821,15074492.0,2018-04-29 00:00:00,0,13472933,15074788.0,112.0,296.0
7,30200,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,04:00:00,REGULAR,13472933,15074788.0,2018-04-29 04:00:00,4,13472995,15075014.0,62.0,226.0
8,30201,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,08:00:00,REGULAR,13472995,15075014.0,2018-04-29 08:00:00,8,13473441,15075731.0,446.0,717.0
9,30202,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,12:00:00,REGULAR,13473441,15075731.0,2018-04-29 12:00:00,12,13474027,15076910.0,586.0,1179.0
10,30203,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,16:00:00,REGULAR,13474027,15076910.0,2018-04-29 16:00:00,16,13474618,15078044.0,591.0,1134.0
11,30204,H007,R248,00-00-00,1 AV,L,BMT,04/29/2018,20:00:00,REGULAR,13474618,15078044.0,2018-04-29 20:00:00,20,13474940,15078584.0,322.0,540.0
12,30205,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,00:00:00,REGULAR,13474940,15078584.0,2018-04-30 00:00:00,0,13474962,15078681.0,22.0,97.0
13,30206,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,04:00:00,REGULAR,13474962,15078681.0,2018-04-30 04:00:00,4,13475296,15079536.0,334.0,855.0
14,30207,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,08:00:00,REGULAR,13475296,15079536.0,2018-04-30 08:00:00,8,13476413,15080969.0,1117.0,1433.0
15,30208,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,12:00:00,REGULAR,13476413,15080969.0,2018-04-30 12:00:00,12,13477408,15081781.0,995.0,812.0
16,30209,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,16:00:00,REGULAR,13477408,15081781.0,2018-04-30 16:00:00,16,13478480,15082614.0,1072.0,833.0
17,30210,H007,R248,00-00-00,1 AV,L,BMT,04/30/2018,20:00:00,REGULAR,13478480,15082614.0,2018-04-30 20:00:00,20,13478886,15083094.0,406.0,480.0
18,30211,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,00:00:00,REGULAR,13478886,15083094.0,2018-05-01 00:00:00,0,13478886,15083094.0,0.0,0.0
19,30212,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,04:00:00,REGULAR,13478886,15083094.0,2018-05-01 04:00:00,4,13479249,15084001.0,363.0,907.0
20,30213,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,08:00:00,REGULAR,13479249,15084001.0,2018-05-01 08:00:00,8,13480288,15085460.0,1039.0,1459.0
21,30214,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,12:00:00,REGULAR,13480288,15085460.0,2018-05-01 12:00:00,12,13481170,15086314.0,882.0,854.0
22,30215,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,16:00:00,REGULAR,13481170,15086314.0,2018-05-01 16:00:00,16,13482278,15087177.0,1108.0,863.0
23,30216,H007,R248,00-00-00,1 AV,L,BMT,05/01/2018,20:00:00,REGULAR,13482278,15087177.0,2018-05-01 20:00:00,20,13482663,15087754.0,385.0,577.0
24,30217,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,00:00:00,REGULAR,13482663,15087754.0,2018-05-02 00:00:00,0,13482705,15087837.0,42.0,83.0
25,30218,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,04:00:00,REGULAR,13482705,15087837.0,2018-05-02 04:00:00,4,13483081,15088712.0,376.0,875.0
26,30219,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,08:00:00,REGULAR,13483081,15088712.0,2018-05-02 08:00:00,8,13484086,15090389.0,1005.0,1677.0
27,30220,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,12:00:00,REGULAR,13484086,15090389.0,2018-05-02 12:00:00,12,13485041,15091188.0,955.0,799.0
28,30221,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,16:00:00,REGULAR,13485041,15091188.0,2018-05-02 16:00:00,16,13486127,15092089.0,1086.0,901.0
29,30222,H007,R248,00-00-00,1 AV,L,BMT,05/02/2018,20:00:00,REGULAR,13486127,15092089.0,2018-05-02 20:00:00,20,13486598,15092679.0,471.0,590.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985370,173152,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,01:00:00,REGULAR,39,103.0,2018-05-28 01:00:00,1,39,103.0,0.0,0.0
985371,173153,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,05:00:00,REGULAR,39,103.0,2018-05-28 05:00:00,5,39,103.0,0.0,0.0
985372,173154,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,09:00:00,REGULAR,39,103.0,2018-05-28 09:00:00,9,39,103.0,0.0,0.0
985373,173155,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,13:00:00,REGULAR,39,103.0,2018-05-28 13:00:00,13,39,103.0,0.0,0.0
985374,173156,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,17:00:00,REGULAR,39,103.0,2018-05-28 17:00:00,17,39,103.0,0.0,0.0
985375,173157,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/28/2018,21:00:00,REGULAR,39,103.0,2018-05-28 21:00:00,21,39,103.0,0.0,0.0
985376,173158,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,01:00:00,REGULAR,39,103.0,2018-05-29 01:00:00,1,39,103.0,0.0,0.0
985377,173159,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,05:00:00,REGULAR,39,103.0,2018-05-29 05:00:00,5,39,103.0,0.0,0.0
985378,173160,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,09:00:00,REGULAR,39,103.0,2018-05-29 09:00:00,9,39,103.0,0.0,0.0
985379,173161,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,13:00:00,REGULAR,39,103.0,2018-05-29 13:00:00,13,39,103.0,0.0,0.0
985380,173162,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,17:00:00,REGULAR,39,103.0,2018-05-29 17:00:00,17,39,103.0,0.0,0.0
985381,173163,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/29/2018,21:00:00,REGULAR,39,103.0,2018-05-29 21:00:00,21,39,103.0,0.0,0.0
985382,173164,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,01:00:00,REGULAR,39,103.0,2018-05-30 01:00:00,1,39,103.0,0.0,0.0
985383,173165,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,05:00:00,REGULAR,39,103.0,2018-05-30 05:00:00,5,39,103.0,0.0,0.0
985384,173166,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,09:00:00,REGULAR,39,103.0,2018-05-30 09:00:00,9,39,103.0,0.0,0.0
985385,173167,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,13:00:00,REGULAR,39,103.0,2018-05-30 13:00:00,13,39,103.0,0.0,0.0
985386,173168,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,17:00:00,REGULAR,39,103.0,2018-05-30 17:00:00,17,39,103.0,0.0,0.0
985387,173169,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/30/2018,21:00:00,REGULAR,39,103.0,2018-05-30 21:00:00,21,39,103.0,0.0,0.0
985388,173170,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,01:00:00,REGULAR,39,103.0,2018-05-31 01:00:00,1,39,103.0,0.0,0.0
985389,173171,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,05:00:00,REGULAR,39,103.0,2018-05-31 05:00:00,5,39,103.0,0.0,0.0
985390,173172,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,09:00:00,REGULAR,39,103.0,2018-05-31 09:00:00,9,39,103.0,0.0,0.0
985391,173173,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,13:00:00,REGULAR,39,103.0,2018-05-31 13:00:00,13,39,103.0,0.0,0.0
985392,173174,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,17:00:00,REGULAR,39,103.0,2018-05-31 17:00:00,17,39,103.0,0.0,0.0
985393,173175,R419,R326,00-05-01,ZEREGA AV,6,IRT,05/31/2018,21:00:00,REGULAR,39,103.0,2018-05-31 21:00:00,21,39,103.0,0.0,0.0
985394,173176,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,01:00:00,REGULAR,39,103.0,2018-06-01 01:00:00,1,39,103.0,0.0,0.0
985395,173177,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,05:00:00,REGULAR,39,103.0,2018-06-01 05:00:00,5,39,103.0,0.0,0.0
985396,173178,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,09:00:00,REGULAR,39,103.0,2018-06-01 09:00:00,9,39,103.0,0.0,0.0
985397,173179,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,13:00:00,REGULAR,39,103.0,2018-06-01 13:00:00,13,39,103.0,0.0,0.0
985398,173180,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,17:00:00,REGULAR,39,103.0,2018-06-01 17:00:00,17,39,103.0,0.0,0.0
985399,173181,R419,R326,00-05-01,ZEREGA AV,6,IRT,06/01/2018,21:00:00,REGULAR,39,103.0,2018-06-01 21:00:00,21,NaN,NaN,NaN,NaN

In [33]:
entry.rename(columns={'STATION':'stations'}, inplace = True)

In [34]:
new_entry = entry.loc[:,['stations','hourly_entries','hourly_exits']]

In [35]:
new_entry

         stations  hourly_entries  hourly_exits
0            1 AV            90.0         294.0
1            1 AV            89.0         321.0
2            1 AV           546.0        1039.0
3            1 AV           741.0        1288.0
4            1 AV           693.0        1560.0
5            1 AV           505.0        1022.0
6            1 AV           112.0         296.0
7            1 AV            62.0         226.0
8            1 AV           446.0         717.0
9            1 AV           586.0        1179.0
10           1 AV           591.0        1134.0
11           1 AV           322.0         540.0
12           1 AV            22.0          97.0
13           1 AV           334.0         855.0
14           1 AV          1117.0        1433.0
15           1 AV           995.0         812.0
16           1 AV          1072.0         833.0
17           1 AV           406.0         480.0
18           1 AV             0.0           0.0
19           1 AV           363.0         907.0
20           1 AV          1039.0        1459.0
21           1 AV           882.0         854.0
22           1 AV          1108.0         863.0
23           1 AV           385.0         577.0
24           1 AV            42.0          83.0
25           1 AV           376.0         875.0
26           1 AV          1005.0        1677.0
27           1 AV           955.0         799.0
28           1 AV          1086.0         901.0
29           1 AV           471.0         590.0
...           ...             ...           ...
985370  ZEREGA AV             0.0           0.0
985371  ZEREGA AV             0.0           0.0
985372  ZEREGA AV             0.0           0.0
985373  ZEREGA AV             0.0           0.0
985374  ZEREGA AV             0.0           0.0
985375  ZEREGA AV             0.0           0.0
985376  ZEREGA AV             0.0           0.0
985377  ZEREGA AV             0.0           0.0
985378  ZEREGA AV             0.0           0.0
985379  ZEREGA AV             0.0           0.0
985380  ZEREGA AV             0.0           0.0
985381  ZEREGA AV             0.0           0.0
985382  ZEREGA AV             0.0           0.0
985383  ZEREGA AV             0.0           0.0
985384  ZEREGA AV             0.0           0.0
985385  ZEREGA AV             0.0           0.0
985386  ZEREGA AV             0.0           0.0
985387  ZEREGA AV             0.0           0.0
985388  ZEREGA AV             0.0           0.0
985389  ZEREGA AV             0.0           0.0
985390  ZEREGA AV             0.0           0.0
985391  ZEREGA AV             0.0           0.0
985392  ZEREGA AV             0.0           0.0
985393  ZEREGA AV             0.0           0.0
985394  ZEREGA AV             0.0           0.0
985395  ZEREGA AV             0.0           0.0
985396  ZEREGA AV             0.0           0.0
985397  ZEREGA AV             0.0           0.0
985398  ZEREGA AV             0.0           0.0
985399  ZEREGA AV             NaN           NaN

[985400 rows x 3 columns]

In [36]:
scores = new_entry.merge(com_count,on = 'stations')

In [37]:
scores

Empty DataFrame
Columns: [stations, hourly_entries, hourly_exits, COMPANY, distance]
Index: []

In [38]:
com_count

                                   COMPANY  distance
stations
Times Sq - 42nd St                       8         8
23rd St                                  3         3
Grand Central - 42nd St                  3         3
28th St                                  2         2
33rd St                                  2         2
Spring St                                2         2
Herald Sq - 34th St                      2         2
57th St                                  2         2
Canal St                                 2         2
8th St - NYU                             1         1
Houston St                               1         1
Canal St - Holland Tunnel                1         1
Astor Pl                                 1         1
14th St                                  1         1
7th Ave                                  1         1
18th St                                  1         1
5th Ave - Bryant Pk                      1         1
51st St                                  1         1
42nd St - Port Authority Bus Term        1         1
42nd St - Bryant Pk                      1         1
34th St - Hudson Yards                   1         1
6th Ave                                  1         1